# Generated by Django 3.2.5 on 2021-07-11 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('url', models.CharField(default='', max_length=255)),
                ('topic', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('rooms', models.IntegerField(blank=True, default=0)),
                ('body', models.TextField(blank=True, default='')),
                ('images_count', models.IntegerField(default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('currency', models.IntegerField(blank=True, default=0)),
                ('area', models.IntegerField(blank=True, default=0)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('room_type', models.CharField(blank=True, default='', max_length=100)),
                ('site', models.CharField(choices=[('diesel', 'diesel'), ('lalafo', 'lalafo'), ('house', 'house')], default='', max_length=20)),
                ('floor', models.IntegerField(blank=True, default=0)),
                ('max_floor', models.IntegerField(blank=True, default=0)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.FloatField(blank=True, default=0.0)),
                ('lon', models.FloatField(blank=True, default=0.0)),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, default=0)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('c_type', models.CharField(choices=[('private', 'private'), ('supergroup', 'supergroup')], default='private', max_length=20)),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('enable', models.BooleanField(default=True)),
                ('diesel', models.BooleanField(default=True)),
                ('lalafo', models.BooleanField(default=True)),
                ('house', models.BooleanField(default=True)),
                ('photo', models.BooleanField(default=True)),
                ('usd', models.CharField(default='0:0', max_length=100)),
                ('kgs', models.CharField(default='0:0', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('message_id', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('apartment', 'Apartment'), ('photo', 'Photo'), ('description', 'Description')], default='apartment', max_length=50)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hsearch.apartment')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hsearch.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=255, unique=True)),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hsearch.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('body', models.TextField(default='')),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hsearch.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=False)),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hsearch.apartment')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hsearch.chat')),
            ],
        ),
    ]
