version: '3.7'

services:
  postgres:
    image: postgres:12.2
    container_name: hsearch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: hsearch
      POSTGRES_USER: hsearch
      POSTGRES_DB: hsearch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
