version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: hsearch_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 65432:5432

  admin:
    # image:
    build:
      dockerfile: Dockerfile.admin
      context: .
    container_name: hsearch_admin
    environment:
      DJANGO_SECRET_KEY: 'budbwuhevbw9huvbw92r0fj2n0rfj2n'
      POSTGRES_PASSWORD: 'hsearch'
      POSTGRES_HOST: hsearch_db
      POSTGRES_PORT: 5432
    ports:
      - 8080:8080

volumes:
  pgdata:
