version: '3.3'

services:
  app:
    image: comov/hsearch:v1.2.0
    container_name: hsearch
    restart: always
    env_file:
      - .env
    networks:
      - hsearch
    logging:
      driver: syslog
      options:
        tag: docker/hsearch

  postgres:
    image: postgres:13-alpine
    container_name: hsearch_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hsearch
    logging:
      driver: syslog
      options:
        tag: docker/hsearch_db

volumes:
  pgdata:

networks:
  hsearch:
